version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      PGDATA: /data/postgres
    volumes:
       - ~/.docker-conf/postgres/data/:/data/postgres
    ports:
      - "5432:5432"
    # networks:
    #   - postgres
    restart: unless-stopped

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - ~/.docker-conf/redis/data/:/data     
    ports:
      - "6379:6379"  
    networks:
      - redis

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    networks:
        - rabbitmq
  application:
    build: .
    ports:
        - ${HTTP_PORT}:8000
    env_file:
        - .env    
networks:
  # postgres:
  #   driver: bridge
  rabbitmq:
    driver: bridge
  redis:
    driver: bridge 

volumes:
    postgres:
    rabbitmq:
    redis: